/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndividualsIndexRouteImport } from './routes/individuals.index'
import { Route as AgentsIndexRouteImport } from './routes/agents.index'
import { Route as IndividualsIdRouteImport } from './routes/individuals.$id'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as IndividualsIdPlanPlanIdRouteImport } from './routes/individuals.$id.plan.$planId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIndexRoute = IndividualsIndexRouteImport.update({
  id: '/individuals/',
  path: '/individuals/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsIndexRoute = AgentsIndexRouteImport.update({
  id: '/agents/',
  path: '/agents/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdRoute = IndividualsIdRouteImport.update({
  id: '/individuals/$id',
  path: '/individuals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdPlanPlanIdRoute = IndividualsIdPlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => IndividualsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/individuals/$id': typeof IndividualsIdRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/individuals/$id': typeof IndividualsIdRouteWithChildren
  '/agents': typeof AgentsIndexRoute
  '/individuals': typeof IndividualsIndexRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agents/new': typeof AgentsNewRoute
  '/individuals/$id': typeof IndividualsIdRouteWithChildren
  '/agents/': typeof AgentsIndexRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agents/new'
    | '/individuals/$id'
    | '/agents/'
    | '/individuals/'
    | '/individuals/$id/plan/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agents/new'
    | '/individuals/$id'
    | '/agents'
    | '/individuals'
    | '/individuals/$id/plan/$planId'
  id:
    | '__root__'
    | '/'
    | '/agents/new'
    | '/individuals/$id'
    | '/agents/'
    | '/individuals/'
    | '/individuals/$id/plan/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentsNewRoute: typeof AgentsNewRoute
  IndividualsIdRoute: typeof IndividualsIdRouteWithChildren
  AgentsIndexRoute: typeof AgentsIndexRoute
  IndividualsIndexRoute: typeof IndividualsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/': {
      id: '/individuals/'
      path: '/individuals'
      fullPath: '/individuals/'
      preLoaderRoute: typeof IndividualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/': {
      id: '/agents/'
      path: '/agents'
      fullPath: '/agents/'
      preLoaderRoute: typeof AgentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id': {
      id: '/individuals/$id'
      path: '/individuals/$id'
      fullPath: '/individuals/$id'
      preLoaderRoute: typeof IndividualsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id/plan/$planId': {
      id: '/individuals/$id/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/individuals/$id/plan/$planId'
      preLoaderRoute: typeof IndividualsIdPlanPlanIdRouteImport
      parentRoute: typeof IndividualsIdRoute
    }
  }
}

interface IndividualsIdRouteChildren {
  IndividualsIdPlanPlanIdRoute: typeof IndividualsIdPlanPlanIdRoute
}

const IndividualsIdRouteChildren: IndividualsIdRouteChildren = {
  IndividualsIdPlanPlanIdRoute: IndividualsIdPlanPlanIdRoute,
}

const IndividualsIdRouteWithChildren = IndividualsIdRoute._addFileChildren(
  IndividualsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentsNewRoute: AgentsNewRoute,
  IndividualsIdRoute: IndividualsIdRouteWithChildren,
  AgentsIndexRoute: AgentsIndexRoute,
  IndividualsIndexRoute: IndividualsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
