/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LifeplanRouteImport } from './routes/lifeplan'
import { Route as IndexRouteImport } from './routes/index'
import { Route as IndividualsIndexRouteImport } from './routes/individuals.index'
import { Route as GuidelinesIndexRouteImport } from './routes/guidelines.index'
import { Route as SettingsLibrariesRouteImport } from './routes/settings.libraries'
import { Route as IndividualsIdRouteImport } from './routes/individuals.$id'
import { Route as GuidelinesNewRouteImport } from './routes/guidelines.new'
import { Route as GuidelinesIdRouteImport } from './routes/guidelines.$id'
import { Route as ApiGeneratePlanRouteImport } from './routes/api/generate-plan'
import { Route as AgentsNewRouteImport } from './routes/agents.new'
import { Route as IndividualsIdIndexRouteImport } from './routes/individuals.$id.index'
import { Route as IndividualsIdTrainingsRouteImport } from './routes/individuals.$id.trainings'
import { Route as AgentsIdEditRouteImport } from './routes/agents.$id.edit'
import { Route as IndividualsIdPlanPlanIdRouteImport } from './routes/individuals.$id.plan.$planId'
import { Route as IndividualsIdLogAgentIdRouteImport } from './routes/individuals.$id.log.$agentId'

const LifeplanRoute = LifeplanRouteImport.update({
  id: '/lifeplan',
  path: '/lifeplan',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIndexRoute = IndividualsIndexRouteImport.update({
  id: '/individuals/',
  path: '/individuals/',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIndexRoute = GuidelinesIndexRouteImport.update({
  id: '/guidelines/',
  path: '/guidelines/',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsLibrariesRoute = SettingsLibrariesRouteImport.update({
  id: '/settings/libraries',
  path: '/settings/libraries',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdRoute = IndividualsIdRouteImport.update({
  id: '/individuals/$id',
  path: '/individuals/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesNewRoute = GuidelinesNewRouteImport.update({
  id: '/guidelines/new',
  path: '/guidelines/new',
  getParentRoute: () => rootRouteImport,
} as any)
const GuidelinesIdRoute = GuidelinesIdRouteImport.update({
  id: '/guidelines/$id',
  path: '/guidelines/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGeneratePlanRoute = ApiGeneratePlanRouteImport.update({
  id: '/api/generate-plan',
  path: '/api/generate-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentsNewRoute = AgentsNewRouteImport.update({
  id: '/agents/new',
  path: '/agents/new',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdIndexRoute = IndividualsIdIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => IndividualsIdRoute,
} as any)
const IndividualsIdTrainingsRoute = IndividualsIdTrainingsRouteImport.update({
  id: '/trainings',
  path: '/trainings',
  getParentRoute: () => IndividualsIdRoute,
} as any)
const AgentsIdEditRoute = AgentsIdEditRouteImport.update({
  id: '/agents/$id/edit',
  path: '/agents/$id/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const IndividualsIdPlanPlanIdRoute = IndividualsIdPlanPlanIdRouteImport.update({
  id: '/plan/$planId',
  path: '/plan/$planId',
  getParentRoute: () => IndividualsIdRoute,
} as any)
const IndividualsIdLogAgentIdRoute = IndividualsIdLogAgentIdRouteImport.update({
  id: '/log/$agentId',
  path: '/log/$agentId',
  getParentRoute: () => IndividualsIdRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/lifeplan': typeof LifeplanRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines/new': typeof GuidelinesNewRoute
  '/individuals/$id': typeof IndividualsIdRouteWithChildren
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/individuals/$id/trainings': typeof IndividualsIdTrainingsRoute
  '/individuals/$id/': typeof IndividualsIdIndexRoute
  '/individuals/$id/log/$agentId': typeof IndividualsIdLogAgentIdRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/lifeplan': typeof LifeplanRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines/new': typeof GuidelinesNewRoute
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/guidelines': typeof GuidelinesIndexRoute
  '/individuals': typeof IndividualsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/individuals/$id/trainings': typeof IndividualsIdTrainingsRoute
  '/individuals/$id': typeof IndividualsIdIndexRoute
  '/individuals/$id/log/$agentId': typeof IndividualsIdLogAgentIdRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/lifeplan': typeof LifeplanRoute
  '/agents/new': typeof AgentsNewRoute
  '/api/generate-plan': typeof ApiGeneratePlanRoute
  '/guidelines/$id': typeof GuidelinesIdRoute
  '/guidelines/new': typeof GuidelinesNewRoute
  '/individuals/$id': typeof IndividualsIdRouteWithChildren
  '/settings/libraries': typeof SettingsLibrariesRoute
  '/guidelines/': typeof GuidelinesIndexRoute
  '/individuals/': typeof IndividualsIndexRoute
  '/agents/$id/edit': typeof AgentsIdEditRoute
  '/individuals/$id/trainings': typeof IndividualsIdTrainingsRoute
  '/individuals/$id/': typeof IndividualsIdIndexRoute
  '/individuals/$id/log/$agentId': typeof IndividualsIdLogAgentIdRoute
  '/individuals/$id/plan/$planId': typeof IndividualsIdPlanPlanIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/lifeplan'
    | '/agents/new'
    | '/api/generate-plan'
    | '/guidelines/$id'
    | '/guidelines/new'
    | '/individuals/$id'
    | '/settings/libraries'
    | '/guidelines/'
    | '/individuals/'
    | '/agents/$id/edit'
    | '/individuals/$id/trainings'
    | '/individuals/$id/'
    | '/individuals/$id/log/$agentId'
    | '/individuals/$id/plan/$planId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/lifeplan'
    | '/agents/new'
    | '/api/generate-plan'
    | '/guidelines/$id'
    | '/guidelines/new'
    | '/settings/libraries'
    | '/guidelines'
    | '/individuals'
    | '/agents/$id/edit'
    | '/individuals/$id/trainings'
    | '/individuals/$id'
    | '/individuals/$id/log/$agentId'
    | '/individuals/$id/plan/$planId'
  id:
    | '__root__'
    | '/'
    | '/lifeplan'
    | '/agents/new'
    | '/api/generate-plan'
    | '/guidelines/$id'
    | '/guidelines/new'
    | '/individuals/$id'
    | '/settings/libraries'
    | '/guidelines/'
    | '/individuals/'
    | '/agents/$id/edit'
    | '/individuals/$id/trainings'
    | '/individuals/$id/'
    | '/individuals/$id/log/$agentId'
    | '/individuals/$id/plan/$planId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LifeplanRoute: typeof LifeplanRoute
  AgentsNewRoute: typeof AgentsNewRoute
  ApiGeneratePlanRoute: typeof ApiGeneratePlanRoute
  GuidelinesIdRoute: typeof GuidelinesIdRoute
  GuidelinesNewRoute: typeof GuidelinesNewRoute
  IndividualsIdRoute: typeof IndividualsIdRouteWithChildren
  SettingsLibrariesRoute: typeof SettingsLibrariesRoute
  GuidelinesIndexRoute: typeof GuidelinesIndexRoute
  IndividualsIndexRoute: typeof IndividualsIndexRoute
  AgentsIdEditRoute: typeof AgentsIdEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/lifeplan': {
      id: '/lifeplan'
      path: '/lifeplan'
      fullPath: '/lifeplan'
      preLoaderRoute: typeof LifeplanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/': {
      id: '/individuals/'
      path: '/individuals'
      fullPath: '/individuals/'
      preLoaderRoute: typeof IndividualsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/': {
      id: '/guidelines/'
      path: '/guidelines'
      fullPath: '/guidelines/'
      preLoaderRoute: typeof GuidelinesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings/libraries': {
      id: '/settings/libraries'
      path: '/settings/libraries'
      fullPath: '/settings/libraries'
      preLoaderRoute: typeof SettingsLibrariesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id': {
      id: '/individuals/$id'
      path: '/individuals/$id'
      fullPath: '/individuals/$id'
      preLoaderRoute: typeof IndividualsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/new': {
      id: '/guidelines/new'
      path: '/guidelines/new'
      fullPath: '/guidelines/new'
      preLoaderRoute: typeof GuidelinesNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guidelines/$id': {
      id: '/guidelines/$id'
      path: '/guidelines/$id'
      fullPath: '/guidelines/$id'
      preLoaderRoute: typeof GuidelinesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-plan': {
      id: '/api/generate-plan'
      path: '/api/generate-plan'
      fullPath: '/api/generate-plan'
      preLoaderRoute: typeof ApiGeneratePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agents/new': {
      id: '/agents/new'
      path: '/agents/new'
      fullPath: '/agents/new'
      preLoaderRoute: typeof AgentsNewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id/': {
      id: '/individuals/$id/'
      path: '/'
      fullPath: '/individuals/$id/'
      preLoaderRoute: typeof IndividualsIdIndexRouteImport
      parentRoute: typeof IndividualsIdRoute
    }
    '/individuals/$id/trainings': {
      id: '/individuals/$id/trainings'
      path: '/trainings'
      fullPath: '/individuals/$id/trainings'
      preLoaderRoute: typeof IndividualsIdTrainingsRouteImport
      parentRoute: typeof IndividualsIdRoute
    }
    '/agents/$id/edit': {
      id: '/agents/$id/edit'
      path: '/agents/$id/edit'
      fullPath: '/agents/$id/edit'
      preLoaderRoute: typeof AgentsIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/individuals/$id/plan/$planId': {
      id: '/individuals/$id/plan/$planId'
      path: '/plan/$planId'
      fullPath: '/individuals/$id/plan/$planId'
      preLoaderRoute: typeof IndividualsIdPlanPlanIdRouteImport
      parentRoute: typeof IndividualsIdRoute
    }
    '/individuals/$id/log/$agentId': {
      id: '/individuals/$id/log/$agentId'
      path: '/log/$agentId'
      fullPath: '/individuals/$id/log/$agentId'
      preLoaderRoute: typeof IndividualsIdLogAgentIdRouteImport
      parentRoute: typeof IndividualsIdRoute
    }
  }
}

interface IndividualsIdRouteChildren {
  IndividualsIdTrainingsRoute: typeof IndividualsIdTrainingsRoute
  IndividualsIdIndexRoute: typeof IndividualsIdIndexRoute
  IndividualsIdLogAgentIdRoute: typeof IndividualsIdLogAgentIdRoute
  IndividualsIdPlanPlanIdRoute: typeof IndividualsIdPlanPlanIdRoute
}

const IndividualsIdRouteChildren: IndividualsIdRouteChildren = {
  IndividualsIdTrainingsRoute: IndividualsIdTrainingsRoute,
  IndividualsIdIndexRoute: IndividualsIdIndexRoute,
  IndividualsIdLogAgentIdRoute: IndividualsIdLogAgentIdRoute,
  IndividualsIdPlanPlanIdRoute: IndividualsIdPlanPlanIdRoute,
}

const IndividualsIdRouteWithChildren = IndividualsIdRoute._addFileChildren(
  IndividualsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LifeplanRoute: LifeplanRoute,
  AgentsNewRoute: AgentsNewRoute,
  ApiGeneratePlanRoute: ApiGeneratePlanRoute,
  GuidelinesIdRoute: GuidelinesIdRoute,
  GuidelinesNewRoute: GuidelinesNewRoute,
  IndividualsIdRoute: IndividualsIdRouteWithChildren,
  SettingsLibrariesRoute: SettingsLibrariesRoute,
  GuidelinesIndexRoute: GuidelinesIndexRoute,
  IndividualsIndexRoute: IndividualsIndexRoute,
  AgentsIdEditRoute: AgentsIdEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
